---
# defaults file for vault-auto-auth

# true to install from ansible control
vault_agent_start: true

vault_install_from_control: true
vault_user: vault
vault_group: bin
vault_enterprise_premium: false
vault_enterprise_premium_hsm: false

vault_version: "{{ lookup('env','VAULT_VERSION') | default('1.0.0', true) }}{{'+prem' if vault_enterprise_premium else '' }}{{'.hsm' if vault_enterprise_premium_hsm else '' }}"
vault_architecture_map:
  amd64: amd64
  x86_64: amd64
  armv7l: arm
  aarch64: arm64
vault_architecture: "{{ vault_architecture_map[ansible_architecture] }}"
vault_os: "{{ ansible_system|lower }}"
vault_pkg: "vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"
vault_shasums: "vault_{{ vault_version }}_SHA256SUMS"
vault_zip_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"
vault_checksum_file_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version}}_SHA256SUMS"

vault_bin_path: /usr/local/bin
vault_config_path: /etc/vault.d

vault_enterprise: "{{ lookup('env','VAULT_ENTERPRISE') | default(false, true) }}"
vault_enterprie_pkg: "vault-enterprise_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"
vault_enterprise_shasums: "vault-enterprise_{{ vault_version }}_SHA256SUMS"

agent_remove_secret: true
role_id_dir: /tmp
secret_id_dir: /tmp
token_dir: /tmp
namespace: "{{ lookup('env', 'VAULT_NAMESPACE') | default('') }}"
